---

- hosts: localhost

  tasks:
    - name: Create folders for credentials
      file:
        path: "{{ credentials_path }}/{{ item[1] }}/users/{{ item[0].name }}"
        state: directory
        mode: 0755
      with_nested:
        - "{{ users }}"
        - "{{ groups['servers'] }}"

    - name: Generate superuser SSH keys
      openssh_keypair:
        path: "{{ credentials_path }}/{{ item[1] }}/users/{{ item[0].name }}/id_rsa"
      with_nested:
        - "{{ users }}"
        - "{{ groups['servers'] }}"


- hosts: servers
  become: true

  roles:
    - role: common
    - role: users
