---

- name: Add Helm apt-key
  apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present

- name: Add Helm APT repository
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present
    filename: helm

- name: Unhold packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: install
  with_items:
    - helm

- name: Install Helm
  apt:
    name:
      - "helm={{ helm_version }}"
    state: present
    update_cache: yes

- name: Hold packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - helm
