---

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - binutils
      - curl
      - gcc
      - g++
      - git
      - iptables
      - mc
      - net-tools
      - network-manager
      - tmux
      - zsh
      - python3-passlib
      - python3-setuptools
      - python3-pip
      - sudo
    update_cache: yes
  tags:
    - common

- name: Install python packages
  pip:
    name:
      - jsondiff
      - pyyaml
      - openshift
  tags:
    - common

- import_tasks: locale.yml
  tags:
    - common

- name: Configure timezone
  shell: echo "{{ timezone }}" > /etc/timezone
  become: true
  when: "ansible_distribution == 'Debian'"
  notify: 'apply timezone'
  tags:
    - common

- name: return motd to registered var
  command: "cp /usr/share/zoneinfo/{{ timezone }} /etc/localtime"
  become: true
  when: "ansible_distribution == 'Debian'"
  notify: 'apply timezone'
  tags:
    - common

- name: Connect to private network
  community.general.nmcli:
    conn_name: private-network
    ifname: 'eth1'
    type: ethernet
    ip4: "{{ private_host }}/12"
    mtu: 1450
    state: present
