---

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd

- name: Connect to private network
  community.general.nmcli:
    conn_name: private-network
    ifname: 'eth1'
    type: ethernet
    ip4: "{{ private_host }}/12"
    mtu: 1450
    state: present

- name: Disable ipv6
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
    reload: yes
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
