---

- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: "{{ repo }}"

- name: Add namespace
  kubernetes.core.k8s:
    kind: Namespace
    api_version: v1
    name: "{{ namespace }}"
    state: present
